spring:
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:54321/transactions-db}
        username: ${DATABASE_USERNAME_APP:transactions-app}
        password: ${DATABASE_PASSWORD_APP}